# Data Gathering

## Importing

### CSV

# Importing a CSV File

## What is a CSV File?

**CSV** stands for **Comma-Separated Values**.

- It is one of the most commonly used file formats for storing tabular data.
- Data is stored in rows and columns.
- Each value in a row is separated by a comma (`,`).
- It is widely used because it is simple, lightweight, and supported by almost every data analysis tool.

### Example (students.csv)

```csv
ID,Name,Age,Marks
101,Amit,20,85
102,Priya,21,90
103,Rahul,19,78
```

---

# Syntax to Import a CSV File

```python
import pandas as pd

df = pd.read_csv("students.csv")
```

---

# Syntax Breakdown

```python
import pandas as pd
```

- `import` → Imports a Python library.
- `pandas` → Powerful library used for data analysis.
- `as pd` → Creates a short alias `pd` for easier coding.

---

```python
df = pd.read_csv("students.csv")
```

### Explanation

- `df`
  - Variable that stores the imported dataset.
  - `df` stands for **DataFrame**.

- `pd`
  - Alias of the Pandas library.

- `read_csv()`
  - Pandas function used to read CSV files.
  - Converts the CSV data into a **DataFrame**.

- `"students.csv"`
  - Name (or path) of the CSV file.
  - If the file is in another folder, provide the full or relative path.

Example:

```python
df = pd.read_csv("C:/Users/Student/Documents/students.csv")
```

---

# View the Imported Data

```python
print(df)
```

or

```python
df
```

---

# Display the First 5 Rows

```python
df.head()
```

---

# Display the Last 5 Rows

```python
df.tail()
```

---

# Display Dataset Information

```python
df.info()
```

Shows:

- Number of rows
- Number of columns
- Column names
- Data types
- Missing values

---

# Display Statistical Summary

```python
df.describe()
```

Returns:

- Count
- Mean
- Standard Deviation
- Minimum Value
- Maximum Value
- Quartiles (25%, 50%, 75%)

---

# Display Column Names

```python
df.columns
```

---

# Display Shape of Dataset

```python
df.shape
```

Output:

```python
(rows, columns)
```

Example:

```python
(100, 5)
```

Means:

- 100 rows
- 5 columns

---

# Common Parameters of `read_csv()`

### Read only first 10 rows

```python
df = pd.read_csv("students.csv", nrows=10)
```

---

### Read selected columns

```python
df = pd.read_csv("students.csv", usecols=["Name", "Marks"])
```

---

### Change separator

If values are separated by a semicolon (`;`):

```python
df = pd.read_csv("students.csv", sep=";")
```

---

### Read file without header

```python
df = pd.read_csv("students.csv", header=None)
```

---

### Set a column as index

```python
df = pd.read_csv("students.csv", index_col="ID")
```

---

# Complete Example

```python
import pandas as pd

# Import CSV file
df = pd.read_csv("students.csv")

# Display first five rows
print(df.head())

# Display dataset information
print(df.info())

# Display statistical summary
print(df.describe())
```

---

# Summary

| Function | Purpose |
|----------|---------|
| `import pandas as pd` | Imports the Pandas library |
| `pd.read_csv()` | Reads a CSV file |
| `df.head()` | Displays the first 5 rows |
| `df.tail()` | Displays the last 5 rows |
| `df.info()` | Shows dataset information |
| `df.describe()` | Displays statistical summary |
| `df.columns` | Shows column names |
| `df.shape` | Returns the number of rows and columns |

---

In [2]:
import pandas as pd

In [7]:
# File present on our local machine
df = pd.read_csv("aug_train.csv")
df.head(2)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0

In [27]:
# Import from any online source
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/Shimanshuco/DataScience_ML_GenAI26/main/02%20Libraries/02%20Pandas/01%20Pandas%20Series/subs.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

In [28]:
df = pd.read_csv(data)
df.head(2)

   Subscribers gained
0                  48
1                  57

In [32]:
# sep 
df = pd.read_csv("movie_titles_metadata.tsv",sep="\t")
df
#but here the first col becomes the heading

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [35]:
# sep with names attribute
df = pd.read_csv("movie_titles_metadata.tsv",sep="\t",names=['S.No','Name','release_year','Rating','votes','genres'])
df

,S.No,Name,release_year,Rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [39]:
# index_col parameter
df = pd.read_csv("aug_train.csv")
df.head(2)
df = pd.read_csv("aug_train.csv",index_col='enrollee_id')
df.head(2)

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0

In [40]:
# header parameter
test = pd.read_csv("test.csv")

In [41]:
test

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [42]:
test = pd.read_csv("test.csv",header=1)
test

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [43]:
# use_col paramters

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [47]:
df = pd.read_csv("aug_train.csv",usecols=['enrollee_id','gender','education_level'])
df

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

In [51]:
# squeeze 

s = pd.read_csv("aug_train.csv").squeeze("columns")
print(s)

       enrollee_id      city  city_development_index gender  \
0             8949  city_103                   0.920   Male
1            29725   city_40                   0.776   Male
2            11561   city_21                   0.624    NaN
3            33241  city_115                   0.789    NaN
4              666  city_162                   0.767   Male
...            ...       ...                     ...    ...
19153         7386  city_173                   0.878   Male
19154        31398  city_103                   0.920   Male
19155        24576  city_103                   0.920   Male
19156         5756   city_65                   0.802   Male
19157        23834   city_67                   0.855    NaN

           relevent_experience enrolled_university education_level  \
0      Has relevent experience       no_enrollment        Graduate
1       No relevent experience       no_enrollment        Graduate
2       No relevent experience    Full time course        Graduate
3       No relevent experience                 NaN        Graduate
4      Has relevent experience       no_enrollment         Masters
...                        ...                 ...             ...
19153   No relevent experience       no_enrollment        Graduate
19154  Has relevent experience       no_enrollment        Graduate
19155  Has relevent experience       no_enrollment        Graduate
19156  Has relevent experience       no_enrollment     High School
19157   No relevent experience       no_enrollment  Primary School

      major_discipline experience company_size    company_type last_new_job  \
0                 STEM        >20          NaN             NaN            1
1                 STEM         15        50-99         Pvt Ltd           >4
2                 STEM          5          NaN             NaN        never
3      Business Degree         <1          NaN         Pvt Ltd        never
4                 STEM        >20        50-99  Funded Startup            4
...                ...        ...          ...             ...          ...
19153       Humanities         14          NaN             NaN            1
19154             STEM         14          NaN             NaN            4
19155             STEM        >20        50-99         Pvt Ltd            4
19156              NaN         <1      500-999         Pvt Ltd            2
19157              NaN          2          NaN             NaN            1

       training_hours  target
0                  36     1.0
1                  47     0.0
2                  83     0.0
3                  52     1.0
4                   8     0.0
...               ...     ...
19153              42     1.0
19154              52     1.0
19155              44     0.0
19156              97     0.0
19157             127     0.0

[19158 rows x 14 columns]

In [54]:
# Skiprows/nrows Parameter 
pd.read_csv('aug_train.csv',skiprows=[1,2,5])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
3,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
4,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19150,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19151,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19152,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19153,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19154,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [55]:
pd.read_csv('aug_train.csv',nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

In [57]:
# Encoding parameter
pd.read_csv('zomato.csv')

# UnicodeDecodeError

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 7044: invalid continuation byte

In [58]:
pd.read_csv('zomato.csv',encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [59]:
# Skip bad lines
data = """ID,Name,Marks
101,Amit,85
102,Priya,90
103,Rahul,78,Delhi
104,Neha,88
105,Rohan,91"""

with open("students.csv", "w") as file:
    file.write(data)


# Reading CSV normally (will give ParserError)
# df = pd.read_csv("students.csv")


# Skip bad lines using on_bad_lines="skip"
df = pd.read_csv("students.csv", on_bad_lines="skip")

print(df)

    ID   Name  Marks
0  101   Amit     85
1  102  Priya     90
2  104   Neha     88
3  105  Rohan     91

In [60]:
# dtypes parameter
pd.read_csv('aug_train.csv',dtype={'target':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int32
dtypes: float64(1), int32(1), int64(2), object(10)
memory usage: 2.0+ MB

In [62]:
# Handling Dates
pd.read_csv('IPL Matches 2008-2020.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [63]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [67]:
# Import pandas library
import pandas as pd

# Create DataFrame with separate date columns
data = {
    "day": [15, 20, 5, 10],
    "month": [8, 9, 10, 11],
    "year": [2024, 2024, 2025, 2025]
}

df = pd.DataFrame(data)

# Display original DataFrame
print("Original DataFrame:")
print(df)


# Combine day, month, and year columns into one date column
df["date"] = pd.to_datetime(
    df[["year", "month", "day"]]
)

# Display updated DataFrame
print("\nDataFrame after combining date columns:")
print(df)


# Check data type of date column
print("\nData Types:")
print(df.dtypes)

print("\nExtracted Date Information:")
print(df)
print(df.info())

Original DataFrame:
   day  month  year
0   15      8  2024
1   20      9  2024
2    5     10  2025
3   10     11  2025

DataFrame after combining date columns:
   day  month  year       date
0   15      8  2024 2024-08-15
1   20      9  2024 2024-09-20
2    5     10  2025 2025-10-05
3   10     11  2025 2025-11-10

Data Types:
day               int64
month             int64
year              int64
date     datetime64[ns]
dtype: object

Extracted Date Information:
   day  month  year       date
0   15      8  2024 2024-08-15
1   20      9  2024 2024-09-20
2    5     10  2025 2025-10-05
3   10     11  2025 2025-11-10
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   day     4 non-null      int64
 1   month   4 non-null      int64
 2   year    4 non-null      int64
 3   date    4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(3)
memory usage: 260.0 bytes
None

In [74]:
# Convertors
def rename(name):
    if name == "Chennai Super Kings":
        return "CSK"
    else:
        return name
pd.read_csv('IPL Matches 2008-2020.csv',converters={'team2':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,CSK,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [76]:
# na_values parameter
pd.read_csv('aug_train.csv',na_values=['Male',])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [79]:
# Loading a huge dataset in chunks
dfs = pd.read_csv("aug_train.csv", chunksize=5000)

# Loop through each chunk
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

### Excel

# Reading Excel Files

Pandas provides the `read_excel()` function to import data from Excel files (`.xlsx` or `.xls`) into a DataFrame.

---

# Basic Syntax

```python
import pandas as pd

df = pd.read_excel("filename.xlsx")
```

### Explanation:

- `pd` → Pandas library alias
- `read_excel()` → Function used to read Excel files
- `"filename.xlsx"` → Excel file path
- `df` → Stores the data as a DataFrame

---

# Example Excel File (`students.xlsx`)

| ID | Name | Age | Marks |
|----|------|-----|-------|
| 101 | Amit | 21 | 85 |
| 102 | Priya | 22 | 90 |
| 103 | Rahul | 20 | 78 |

---

# 1. Read Excel File

```python
import pandas as pd

df = pd.read_excel("students.xlsx")

print(df)
```

Output:

```
    ID   Name  Age  Marks
0  101   Amit   21     85
1  102  Priya   22     90
2  103  Rahul   20     78
```

---

# 2. Read Specific Sheet

Excel files can contain multiple sheets.

Syntax:

```python
df = pd.read_excel(
    "students.xlsx",
    sheet_name="Sheet1"
)
```

Example:

```python
df = pd.read_excel(
    "students.xlsx",
    sheet_name="Student_Data"
)
```

---

# 3. Read Sheet Using Sheet Index

Sheets can also be selected by their position.

```python
df = pd.read_excel(
    "students.xlsx",
    sheet_name=0
)
```

Meaning:

- `0` → First sheet
- `1` → Second sheet
- `2` → Third sheet

---

# 4. Read All Sheets

Use:

```python
df = pd.read_excel(
    "students.xlsx",
    sheet_name=None
)
```

Output:

```python
{
'Sheet1': DataFrame,
'Sheet2': DataFrame
}
```

It returns a dictionary of DataFrames.

---

# 5. Read Specific Columns

Use `usecols`.

```python
df = pd.read_excel(
    "students.xlsx",
    usecols=["Name", "Marks"]
)
```

Output:

| Name | Marks |
|------|-------|
| Amit | 85 |
| Priya | 90 |

---

# 6. Read Specific Rows

Use `nrows`.

```python
df = pd.read_excel(
    "students.xlsx",
    nrows=5
)
```

Reads only the first 5 rows.

---

# 7. Skip Rows While Reading

Use `skiprows`.

```python
df = pd.read_excel(
    "students.xlsx",
    skiprows=2
)
```

Skips the first 2 rows.

---

# 8. Reading Excel Without Header

If the first row is not a column name:

```python
df = pd.read_excel(
    "students.xlsx",
    header=None
)
```

Pandas will assign default column numbers:

```
0   1      2
Amit 21   85
```

---

# 9. Assign Custom Column Names

```python
df = pd.read_excel(
    "students.xlsx",
    header=None,
    names=["Name", "Age", "Marks"]
)
```

---

# 10. Set Index Column

```python
df = pd.read_excel(
    "students.xlsx",
    index_col="ID"
)
```

Output:

```
      Name   Age  Marks
ID
101   Amit   21    85
102   Priya  22    90
```

---

# 11. Read Date Columns

If Excel contains dates:

```python
df = pd.read_excel(
    "students.xlsx",
    parse_dates=["Joining_Date"]
)
```

Pandas converts the column into datetime format.

---

# 12. Specify Data Types

Use `dtype`.

```python
df = pd.read_excel(
    "students.xlsx",
    dtype={"ID": str}
)
```

Example:

Before:

```
101
```

After:

```
"101"
```

---

# 13. Handle Missing Values

```python
df = pd.read_excel(
    "students.xlsx",
    na_values=["NA", "Missing", "-"]
)
```

These values will be treated as `NaN`.

---

# 14. Read Excel From a URL

```python
url = "https://example.com/students.xlsx"

df = pd.read_excel(url)
```

---

# 15. Read Large Excel Files

Read only required columns:

```python
df = pd.read_excel(
    "large_file.xlsx",
    usecols=["Name", "Salary"]
)
```

This reduces memory usage.

---

# Complete Example

```python
import pandas as pd

df = pd.read_excel(
    "students.xlsx",
    sheet_name="Student_Data",
    usecols=["Name", "Marks"],
    nrows=10
)

print(df)
```

---

# Important Parameters of `read_excel()`

| Parameter | Purpose |
|-----------|---------|
| `io` | Excel file path |
| `sheet_name` | Select sheet |
| `usecols` | Read selected columns |
| `nrows` | Read limited rows |
| `skiprows` | Skip rows |
| `header` | Define header row |
| `names` | Custom column names |
| `index_col` | Set index column |
| `dtype` | Specify data type |
| `parse_dates` | Convert columns to dates |
| `na_values` | Define missing values |

---

In [83]:
pd.read_excel('students.xlsx')

    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
3   Neha   23     88

### Text-file

# Reading Text Files 

## What is a Text File?

A **text file (`.txt`)** stores data in plain text format.

Examples:

```
students.txt
employees.txt
sales.txt
```

Text files can store data separated by:

- Comma (`,`)
- Tab (`\t`)
- Space
- Semicolon (`;`)
- Other delimiters

Pandas can read text files using the `read_csv()` function because a text file is also a type of delimited file.

---

# Basic Syntax

```python
import pandas as pd

df = pd.read_csv("filename.txt")
```

---

# Example Text File (`students.txt`)

```
ID,Name,Marks
101,Amit,85
102,Priya,90
103,Rahul,78
```

---

# Read Text File

```python
import pandas as pd

df = pd.read_csv("students.txt")

print(df)
```

### Output:

```
    ID    Name  Marks
0  101    Amit     85
1  102   Priya     90
2  103   Rahul     78
```

---

# Text File with Different Separator

## Example: Tab Separated File

`students.txt`

```
ID	Name	Marks
101	Amit	85
102	Priya	90
103	Rahul	78
```

Use `sep="\t"`:

```python
df = pd.read_csv(
    "students.txt",
    sep="\t"
)

print(df)
```

---

# Text File with Space Separator

Example:

```
ID Name Marks
101 Amit 85
102 Priya 90
103 Rahul 78
```

Syntax:

```python
df = pd.read_csv(
    "students.txt",
    sep=" "
)
```

---

# Text File Without Header

If the first row does not contain column names:

```python
df = pd.read_csv(
    "students.txt",
    header=None
)
```

Output:

```
     0       1      2
0   101    Amit    85
1   102   Priya    90
```

---

# Add Custom Column Names

```python
df = pd.read_csv(
    "students.txt",
    header=None,
    names=["ID", "Name", "Marks"]
)
```

Output:

```
    ID   Name  Marks
0  101   Amit     85
1  102  Priya     90
```

---

# Read Selected Columns

Use `usecols`:

```python
df = pd.read_csv(
    "students.txt",
    usecols=["Name", "Marks"]
)
```

---

# Skip Rows

```python
df = pd.read_csv(
    "students.txt",
    skiprows=2
)
```

Skips the first two rows.

---

# Read Limited Rows

```python
df = pd.read_csv(
    "students.txt",
    nrows=5
)
```

Reads only the first 5 rows.

---

# Handle Missing Values

```python
df = pd.read_csv(
    "students.txt",
    na_values=["NA", "Missing"]
)
```

Converts these values into `NaN`.

---

# Complete Example

```python
import pandas as pd

# Read text file
df = pd.read_csv(
    "students.txt",
    sep=","
)

# Display data
print(df)

# Display information
print(df.info())

# Display summary
print(df.describe())
```

---

# Writing DataFrame to a Text File

Pandas can also save data as a text file.

```python
df.to_csv(
    "output.txt",
    sep="\t",
    index=False
)
```

Explanation:

- `to_csv()` → Writes DataFrame to file
- `sep="\t"` → Saves data as tab-separated
- `index=False` → Removes index column

---

# Important Parameters of `read_csv()` for Text Files

| Parameter | Purpose |
|-----------|---------|
| `filepath` | File location |
| `sep` | Separator/delimiter |
| `header` | Header row |
| `names` | Custom column names |
| `usecols` | Select columns |
| `nrows` | Number of rows to read |
| `skiprows` | Skip rows |
| `dtype` | Set data types |
| `na_values` | Define missing values |
| `encoding` | File encoding |

---

### json

# Reading JSON Files

## What is a JSON File?

**JSON (JavaScript Object Notation)** is a lightweight format used to store and exchange data.

JSON data is stored in:

- Key-value pairs
- Arrays
- Nested objects

It is commonly used in:
- APIs
- Web applications
- Data exchange between systems

File extension:

```
.json
```

---

# Example JSON File (`students.json`)

```json
[
    {
        "ID": 101,
        "Name": "Amit",
        "Age": 21,
        "Marks": 85
    },
    {
        "ID": 102,
        "Name": "Priya",
        "Age": 22,
        "Marks": 90
    },
    {
        "ID": 103,
        "Name": "Rahul",
        "Age": 20,
        "Marks": 78
    }
]
```

---

# Import JSON File Using Pandas

## Syntax

```python
import pandas as pd

df = pd.read_json("filename.json")
```

---

# Example

```python
import pandas as pd

df = pd.read_json("students.json")

print(df)
```

### Output:

```
    ID    Name  Age  Marks
0  101    Amit   21     85
1  102   Priya   22     90
2  103   Rahul   20     78
```

---

# JSON From Online URL

Pandas can directly read JSON data from a URL.

```python
import pandas as pd

url = "https://example.com/data.json"

df = pd.read_json(url)

print(df)
```

---

# JSON Orientation (`orient` Parameter)

JSON can store data in different formats.

The `orient` parameter tells Pandas how JSON data is structured.

---

## 1. Records Format

Example:

```json
[
 {"Name":"Amit","Age":21},
 {"Name":"Priya","Age":22}
]
```

Read:

```python
df = pd.read_json(
    "students.json",
    orient="records"
)
```

---

## 2. Columns Format

Example:

```json
{
 "Name":{
    "0":"Amit",
    "1":"Priya"
 },
 "Age":{
    "0":21,
    "1":22
 }
}
```

Read:

```python
df = pd.read_json(
    "students.json",
    orient="columns"
)
```

---

## 3. Index Format

```python
df = pd.read_json(
    "students.json",
    orient="index"
)
```

---

# Read Nested JSON

Example:

```json
{
 "students": [
    {
      "Name":"Amit",
      "Marks":85
    },
    {
      "Name":"Priya",
      "Marks":90
    }
 ]
}
```

Use:

```python
import pandas as pd

df = pd.json_normalize(data["students"])

print(df)
```

Output:

```
    Name  Marks
0   Amit     85
1  Priya     90
```

---

# JSON with `json.loads()`

When JSON data comes as a string:

```python
import pandas as pd
import json

data = '''
[
 {"Name":"Amit","Marks":85},
 {"Name":"Priya","Marks":90}
]
'''

data = json.loads(data)

df = pd.DataFrame(data)

print(df)
```

---

# Convert DataFrame to JSON

Use:

```python
df.to_json("students.json")
```

---

# Convert JSON With Records Format

```python
df.to_json(
    "students.json",
    orient="records"
)
```

Output:

```json
[
 {"Name":"Amit","Marks":85},
 {"Name":"Priya","Marks":90}
]
```

---

# Complete Example

```python
import pandas as pd

# Read JSON file
df = pd.read_json("students.json")

# Display Data
print(df)

# Display information
print(df.info())

# Statistical summary
print(df.describe())
```

---

# Important Functions

| Function | Purpose |
|----------|---------|
| `pd.read_json()` | Reads JSON file into DataFrame |
| `pd.json_normalize()` | Converts nested JSON into tabular format |
| `df.to_json()` | Writes DataFrame as JSON |
| `orient` | Defines JSON structure |

---

In [84]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [85]:
pd.read_json('https://hp-api.onrender.com/api/characters')

,id,name,alternate_names,species,gender,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,hairColour,wand,patronus,hogwartsStudent,hogwartsStaff,actor,alternate_actors,alive,image
0,9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8,Harry Potter,"[The Boy Who Lived, The Chosen One, Undesirabl...",human,male,Gryffindor,31-07-1980,1980.0,True,half-blood,green,black,"{'wood': 'holly', 'core': 'phoenix tail feathe...",stag,True,False,Daniel Radcliffe,[],True,https://ik.imagekit.io/hpapi/harry.jpg
1,4c7e6819-a91a-45b2-a454-f931e4a7cce3,Hermione Granger,"[Hermy, Know-it-all, Miss Grant, Herm-own-ninny]",human,female,Gryffindor,19-09-1979,1979.0,True,muggleborn,brown,brown,"{'wood': 'vine', 'core': 'dragon heartstring',...",otter,True,False,Emma Watson,[],True,https://ik.imagekit.io/hpapi/hermione.jpeg
2,c3b1f9a5-b87b-48bf-b00d-95b093ea6390,Ron Weasley,"[Dragomir Despard, Ronald, Ickle Ronniekins, R...",human,male,Gryffindor,01-03-1980,1980.0,True,pure-blood,blue,red,"{'wood': 'willow', 'core': 'unicorn tail hair'...",Jack Russell terrier,True,False,Rupert Grint,[],True,https://ik.imagekit.io/hpapi/ron.jpg
3,af95bd8a-dfae-45bb-bc69-533860d34129,Draco Malfoy,[],human,male,Slytherin,05-06-1980,1980.0,True,pure-blood,grey,blonde,"{'wood': 'hawthorn', 'core': 'unicorn tail hai...",,True,False,Tom Felton,[],True,https://ik.imagekit.io/hpapi/draco.jpg
4,ca3827f0-375a-4891-aaa5-f5e8a5bad225,Minerva McGonagall,[],human,female,Gryffindor,04-10-1925,1925.0,True,half-blood,,black,"{'wood': 'fir', 'core': 'dragon heartstring', ...",tabby cat,False,True,Dame Maggie Smith,[],True,https://ik.imagekit.io/hpapi/mcgonagall.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,dcdc063e-cf3e-48fc-b777-65922e899b38,Albus Severus Potter,[Al],human,male,Slytherin,None,NaN,True,half-blood,green,black,"{'wood': '', 'core': '', 'length': None}",,True,False,Arthur Bowen,[],True,
433,e4653b01-76a5-4769-a6a2-1f2efaf89cbb,Rose Weasley,[],human,female,Gryffindor,None,NaN,True,half-blood,,red,"{'wood': '', 'core': '', 'length': None}",,True,False,Helena Barlow,[],True,
434,2b203c7e-7b3d-4f27-8b3c-11473904da73,Hugo Weasley,[],human,male,,None,NaN,True,half-blood,,brown,"{'wood': '', 'core': '', 'length': None}",,True,False,Ryan Turner,[],True,
435,7f2f6207-8998-4f98-92c2-8d02898a82eb,Scorpius Malfoy,[Scorpius Hyperion Malfoy],human,male,Slytherin,None,NaN,True,pure-blood,grey,blond,"{'wood': '', 'core': '', 'length': None}",,True,False,Bertie Gilbert,[],True,
436,57fe29d4-312a-4711-bd9a-c320253d9176,Victoire Weasley,[],human,female,,None,NaN,True,,,blonde,"{'wood': '', 'core': '', 'length': None}",,True,False,,[],True,

# SQL

# Import Data from SQL Database 

## What is SQL Data Import?

In Data Analysis, data is often stored in databases like:

- MySQL
- PostgreSQL
- SQLite
- SQL Server
- Oracle

Pandas can directly read data from SQL databases and convert it into a **DataFrame**.

---

# Required Libraries

```python
import pandas as pd
import sqlite3
```

`sqlite3` is a built-in Python library used to connect with SQLite databases.

For other databases, install connectors:

```bash
pip install mysql-connector-python
```

or

```bash
pip install psycopg2
```

---

# Method 1: Read SQL Table Using SQLite

## Step 1: Create Database Connection

```python
import sqlite3

connection = sqlite3.connect("students.db")
```

---

## Step 2: Read SQL Table

### Syntax:

```python
pd.read_sql(
    "SQL Query",
    connection
)
```

Example:

```python
df = pd.read_sql(
    "SELECT * FROM students",
    connection
)

print(df)
```

---

# Complete Example

```python
import pandas as pd
import sqlite3

# Create connection
connection = sqlite3.connect("students.db")

# Read data from SQL table
df = pd.read_sql(
    "SELECT * FROM students",
    connection
)

# Display DataFrame
print(df)

# Close connection
connection.close()
```

---

# Method 2: Read SQL Query

Instead of reading the complete table, we can use SQL queries.

Example:

```python
df = pd.read_sql(
    """
    SELECT Name, Marks
    FROM students
    WHERE Marks > 80
    """,
    connection
)

print(df)
```

Output:

```
    Name   Marks
0   Amit      85
1  Priya      90
```

---

# Method 3: Read SQL Table Directly

Syntax:

```python
pd.read_sql_table(
    "table_name",
    connection
)
```

Example:

```python
df = pd.read_sql_table(
    "students",
    connection
)
```

---

# Method 4: MySQL Database Connection

Install:

```bash
pip install mysql-connector-python
```

---

## Connect to MySQL

```python
import pandas as pd
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="school"
)
```

---

## Import Data

```python
df = pd.read_sql(
    "SELECT * FROM students",
    connection
)

print(df)
```

---

# Method 5: Using SQLAlchemy (Recommended)

Install:

```bash
pip install sqlalchemy
```

---

## Create Connection

```python
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "sqlite:///students.db"
)
```

---

## Read SQL Data

```python
df = pd.read_sql(
    "SELECT * FROM students",
    engine
)

print(df)
```

---

# Reading Only Required Columns

SQL Query:

```python
df = pd.read_sql(
    """
    SELECT Name, Age
    FROM students
    """,
    connection
)
```

---

# Reading Data with Conditions

```python
df = pd.read_sql(
    """
    SELECT *
    FROM students
    WHERE Age > 20
    """,
    connection
)
```

---

# Writing DataFrame to SQL

Pandas can also export DataFrame into SQL.

Syntax:

```python
df.to_sql(
    "table_name",
    connection
)
```

Example:

```python
df.to_sql(
    "students",
    connection,
    if_exists="replace",
    index=False
)
```

---

# Complete SQL Data Workflow

```python
import pandas as pd
import sqlite3

# Connect database
conn = sqlite3.connect("college.db")

# Read SQL data
df = pd.read_sql(
    "SELECT * FROM students",
    conn
)

# Show data
print(df)

# Close connection
conn.close()
```

---

# Important Pandas SQL Functions

| Function | Purpose |
|----------|---------|
| `pd.read_sql()` | Read SQL query/table into DataFrame |
| `pd.read_sql_table()` | Read complete SQL table |
| `df.to_sql()` | Write DataFrame into SQL database |
| `create_engine()` | Create database connection |

---

In [90]:
import pandas as pd
!pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\users\himanshu kumar singh\anaconda3\lib\site-packages (2.2.9)

In [91]:
import mysql.connector

# connection = mysql.connector.connect(
#     host="localhost",
#     user="root",
#     password="password",
#     database="name"
# )

# Export data in a different file format

## Export as CSV

# Export DataFrame as CSV File 

## What is CSV Export?

CSV (**Comma-Separated Values**) is a common file format used to store tabular data.

Pandas allows us to export a DataFrame into a CSV file using the `to_csv()` function.

---

# Basic Syntax

```python
df.to_csv("filename.csv")
```

### Explanation:

- `df` → Pandas DataFrame
- `to_csv()` → Function used to write DataFrame into CSV file
- `"filename.csv"` → Name of the output CSV file

---

# Example: Create DataFrame

```python
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)
```

Output:

```
    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
```

---

# Export DataFrame as CSV

```python
df.to_csv("students.csv")
```

This creates:

```
students.csv
```

---

# Remove Index Column

By default, Pandas saves the index.

Example:

```python
df.to_csv(
    "students.csv",
    index=False
)
```

Output CSV:

```csv
Name,Age,Marks
Amit,21,85
Priya,22,90
Rahul,20,78
```

---

# Add Custom Separator

Default separator is comma (`,`).

Change separator using `sep`.

Example: Save as semicolon separated file:

```python
df.to_csv(
    "students.csv",
    sep=";",
    index=False
)
```

Output:

```csv
Name;Age;Marks
Amit;21;85
Priya;22;90
Rahul;20;78
```

---

# Export Only Selected Columns

Use `columns`.

```python
df.to_csv(
    "students.csv",
    columns=["Name", "Marks"],
    index=False
)
```

Output:

```csv
Name,Marks
Amit,85
Priya,90
Rahul,78
```

---

# Change Encoding

Useful for special characters.

```python
df.to_csv(
    "students.csv",
    encoding="utf-8",
    index=False
)
```

---

# Export Without Header

Remove column names:

```python
df.to_csv(
    "students.csv",
    header=False,
    index=False
)
```

Output:

```csv
Amit,21,85
Priya,22,90
Rahul,20,78
```

---

# Export Specific Rows

Example:

```python
df.head(2).to_csv(
    "students.csv",
    index=False
)
```

Exports only first 2 rows.

---

# Complete Example

```python
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

# Export DataFrame to CSV
df.to_csv(
    "students.csv",
    index=False
)

print("CSV file exported successfully!")
```

---

# Read Exported CSV File

```python
df = pd.read_csv("students.csv")

print(df)
```

---

# Important Parameters of `to_csv()`

| Parameter | Purpose |
|-----------|---------|
| `path_or_buf` | File name/path |
| `index` | Include or remove index |
| `columns` | Export selected columns |
| `sep` | Change separator |
| `header` | Include column names |
| `encoding` | Set file encoding |
| `mode` | File writing mode |
| `na_rep` | Representation of missing values |

In [92]:
deliveries = pd.read_csv('IPL Matches 2008-2020.csv')

In [93]:
deliveries

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [98]:
temp_df=deliveries.groupby('city')['date'].sum().reset_index()
temp_df

              city                                               date
0        Abu Dhabi  2014-04-162014-04-182014-04-182014-04-212014-0...
1        Ahmedabad  2010-03-152010-03-202010-03-262010-03-282014-0...
2        Bangalore  2008-04-182008-04-262008-04-282008-05-052008-0...
3        Bengaluru  2017-04-082018-04-132018-04-152018-04-212018-0...
4     Bloemfontein                               2009-05-152009-05-17
5        Cape Town  2009-04-182009-04-182009-04-192009-04-192009-0...
6        Centurion  2009-04-282009-04-302009-04-302009-05-062009-0...
7       Chandigarh  2008-04-192008-04-252008-04-272008-05-032008-0...
8          Chennai  2008-04-232008-04-262008-05-022008-05-062008-0...
9          Cuttack  2010-03-192010-03-212012-04-222012-05-012014-0...
10           Delhi  2008-04-192008-04-302008-05-082008-05-152008-0...
11      Dharamsala  2010-04-162010-04-182011-05-152011-05-172011-0...
12           Dubai  2020-09-202020-10-242020-09-302020-10-112020-0...
13          Durban  2009-04-212009-04-232009-04-242009-04-252009-0...
14     East London                     2009-05-012009-05-042009-05-08
15       Hyderabad  2008-04-222008-04-242008-05-012008-05-252008-0...
16          Indore  2011-05-132011-05-152017-04-082017-04-102017-0...
17          Jaipur  2008-04-212008-05-012008-05-042008-05-092008-0...
18    Johannesburg  2009-05-022009-05-032009-05-102009-05-162009-0...
19          Kanpur           2016-05-192016-05-212017-05-102017-05-13
20       Kimberley                     2009-05-092009-05-092009-05-11
21           Kochi  2011-04-092011-04-182011-04-272011-04-302011-0...
22         Kolkata  2008-04-202008-04-292008-05-082008-05-132008-0...
23          Mumbai  2008-04-202008-04-272008-05-042008-05-072008-0...
24          Nagpur                     2010-04-052010-04-102010-04-12
25  Port Elizabeth  2009-04-202009-04-262009-04-272009-05-022009-0...
26            Pune  2012-04-082012-04-142012-04-242012-04-262012-0...
27          Raipur  2013-04-282013-05-012015-05-092015-05-122016-0...
28          Rajkot  2016-04-142016-04-212016-04-242016-05-012016-0...
29          Ranchi  2013-05-122013-05-152014-05-022014-05-132014-0...
30         Sharjah  2020-11-032020-09-222020-10-092020-10-312020-1...
31   Visakhapatnam  2012-04-072012-04-092015-04-162015-04-182015-0...

In [100]:
temp_df.to_csv('City_matches.csv',index=False)

##  Export as Excel file

# Export DataFrame as Excel File

## What is Excel Export?

Pandas allows us to export a DataFrame into an Excel file (`.xlsx`) using the `to_excel()` function.

Excel files are commonly used for:

- Reporting
- Business analysis
- Data sharing
- Data storage

---

# Basic Syntax

```python
df.to_excel("filename.xlsx")
```

### Explanation:

- `df` → Pandas DataFrame
- `to_excel()` → Function used to write DataFrame into Excel
- `"filename.xlsx"` → Name of Excel file

---

# Example: Create DataFrame

```python
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)
```

Output:

```
    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
```

---

# Export DataFrame to Excel

```python
df.to_excel("students.xlsx")
```

Creates:

```
students.xlsx
```

---

# Remove Index Column

By default, Pandas writes the index.

To remove it:

```python
df.to_excel(
    "students.xlsx",
    index=False
)
```

Output in Excel:

| Name | Age | Marks |
|------|-----|-------|
| Amit | 21 | 85 |
| Priya | 22 | 90 |
| Rahul | 20 | 78 |

---

# Specify Sheet Name

Use `sheet_name`.

```python
df.to_excel(
    "students.xlsx",
    sheet_name="Student_Data",
    index=False
)
```

Excel file will contain:

```
Student_Data
```

as the sheet name.

---

# Export Multiple DataFrames into Multiple Sheets

```python
import pandas as pd

students = pd.DataFrame({
    "Name": ["Amit", "Priya"],
    "Marks": [85, 90]
})

teachers = pd.DataFrame({
    "Name": ["John", "Smith"],
    "Subject": ["Math", "Science"]
})


with pd.ExcelWriter("school.xlsx") as writer:
    students.to_excel(
        writer,
        sheet_name="Students",
        index=False
    )

    teachers.to_excel(
        writer,
        sheet_name="Teachers",
        index=False
    )
```

Output Excel:

```
school.xlsx

Sheet 1 → Students
Sheet 2 → Teachers
```

---

# Export Selected Columns

Use `columns`.

```python
df.to_excel(
    "students.xlsx",
    columns=["Name", "Marks"],
    index=False
)
```

Output:

| Name | Marks |
|------|-------|
| Amit | 85 |
| Priya | 90 |
| Rahul | 78 |

---

# Start Writing From Specific Row/Column

Use `startrow` and `startcol`.

```python
df.to_excel(
    "students.xlsx",
    startrow=2,
    startcol=1,
    index=False
)
```

Meaning:

- `startrow=2` → Start from third row
- `startcol=1` → Start from second column

---

# Change Engine

For `.xlsx` files:

```python
df.to_excel(
    "students.xlsx",
    engine="openpyxl",
    index=False
)
```

Install if required:

```bash
pip install openpyxl
```

---

# Complete Example

```python
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

# Export to Excel
df.to_excel(
    "students.xlsx",
    sheet_name="Student_Data",
    index=False
)

print("Excel file created successfully!")
```

---

# Read Exported Excel File

```python
df = pd.read_excel("students.xlsx")

print(df)
```

---

# Important Parameters of `to_excel()`

| Parameter | Purpose |
|-----------|---------|
| `excel_writer` | Excel file path |
| `sheet_name` | Name of Excel sheet |
| `index` | Include/remove index |
| `columns` | Export selected columns |
| `header` | Include column names |
| `startrow` | Starting row position |
| `startcol` | Starting column position |
| `engine` | Excel writing engine |

---

In [102]:
df

    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
3   Neha   23     88

In [103]:
df.to_excel('match_day.xlsx')

In [104]:
with pd.ExcelWriter('output.xlsx') as writer:  
    df.to_excel(writer, sheet_name='Sheet_name_1')
    deliveries.to_excel(writer, sheet_name='Sheet_name_2')

## Export as HTML file

#  Export DataFrame as HTML File 

## What is HTML Export?

HTML (**HyperText Markup Language**) is used to create web pages.

Pandas allows us to convert a DataFrame into an HTML table using the `to_html()` function.

It is useful for:

- Creating reports
- Displaying tables on websites
- Sharing data in browser format

---

# Basic Syntax

```python
df.to_html("filename.html")
```

### Explanation:

- `df` → Pandas DataFrame
- `to_html()` → Converts DataFrame into HTML table
- `"filename.html"` → Output HTML file name

---

# Example: Create DataFrame

```python
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)
```

Output:

```
    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
```

---

# Export DataFrame as HTML

```python
df.to_html("students.html")
```

This creates:

```
students.html
```

When opened in a browser, the DataFrame appears as an HTML table.

---

# Remove Index Column

By default, Pandas includes the index.

```python
df.to_html(
    "students.html",
    index=False
)
```

Output:

```html
<table>
<tr>
<th>Name</th>
<th>Age</th>
<th>Marks</th>
</tr>

<tr>
<td>Amit</td>
<td>21</td>
<td>85</td>
</tr>
</table>
```

---

# Add Table Border

```python
html = df.to_html(
    index=False,
    border=1
)

print(html)
```

Output:

```html
<table border="1">
```

---

# Export Selected Columns

Use `columns`.

```python
df.to_html(
    "students.html",
    columns=["Name", "Marks"],
    index=False
)
```

Output:

| Name | Marks |
|------|-------|
| Amit | 85 |
| Priya | 90 |
| Rahul | 78 |

---

# Add CSS Class

You can add a CSS class to style the table.

```python
df.to_html(
    "students.html",
    index=False,
    classes="table table-striped"
)
```

---

# Convert DataFrame Directly into HTML String

Instead of saving a file:

```python
html_table = df.to_html()

print(html_table)
```

Output:

```html
<table border="1">
<tr>
<th>Name</th>
<th>Age</th>
<th>Marks</th>
</tr>
</table>
```

---

# Complete Example

```python
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

# Export as HTML
df.to_html(
    "students.html",
    index=False,
    border=1
)

print("HTML file created successfully!")
```

---

# Read HTML File Using Pandas

Pandas can also read tables from HTML pages.

```python
tables = pd.read_html("students.html")

df = tables[0]

print(df)
```

`read_html()` returns a list of DataFrames because an HTML page can contain multiple tables.

---

# Important Parameters of `to_html()`

| Parameter | Purpose |
|-----------|---------|
| `buf` | File path or output location |
| `columns` | Export selected columns |
| `index` | Include/remove index |
| `header` | Include column names |
| `border` | Add table border |
| `classes` | Add CSS classes |
| `na_rep` | Representation of missing values |

In [106]:
df.to_html('student_data.html')

## Export as JSON

# Export DataFrame as JSON File

## What is JSON Export?

**JSON (JavaScript Object Notation)** is a lightweight data format used for storing and exchanging data.

Pandas allows us to convert a DataFrame into a JSON file using the `to_json()` function.

Used in:

- APIs
- Web applications
- Data exchange
- Machine Learning pipelines

---

# Basic Syntax

```python
df.to_json("filename.json")
```

### Explanation:

- `df` → Pandas DataFrame
- `to_json()` → Converts DataFrame into JSON format
- `"filename.json"` → Output JSON file name

---

# Example: Create DataFrame

```python
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)
```

Output:

```
    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
```

---

# Export DataFrame as JSON

```python
df.to_json("students.json")
```

Creates:

```
students.json
```

---

# JSON Output (Default Format)

```json
{
    "Name":{
        "0":"Amit",
        "1":"Priya",
        "2":"Rahul"
    },
    "Age":{
        "0":21,
        "1":22,
        "2":20
    },
    "Marks":{
        "0":85,
        "1":90,
        "2":78
    }
}
```

---

# Export JSON Using `orient`

The `orient` parameter controls the structure of JSON output.

---

# 1. Records Format (Most Common)

Each row becomes a JSON object.

```python
df.to_json(
    "students.json",
    orient="records"
)
```

Output:

```json
[
    {
        "Name":"Amit",
        "Age":21,
        "Marks":85
    },
    {
        "Name":"Priya",
        "Age":22,
        "Marks":90
    }
]
```

---

# 2. Columns Format

(Default format)

```python
df.to_json(
    "students.json",
    orient="columns"
)
```

Output:

```json
{
 "Name":{
    "0":"Amit",
    "1":"Priya"
 }
}
```

---

# 3. Index Format

```python
df.to_json(
    "students.json",
    orient="index"
)
```

Output:

```json
{
 "0":{
    "Name":"Amit",
    "Age":21
 }
}
```

---

# 4. Split Format

Separates index, columns, and data.

```python
df.to_json(
    "students.json",
    orient="split"
)
```

Output:

```json
{
 "columns":["Name","Age","Marks"],
 "data":[
    ["Amit",21,85],
    ["Priya",22,90]
 ]
}
```

---

# 5. Values Format

Only exports values.

```python
df.to_json(
    "students.json",
    orient="values"
)
```

Output:

```json
[
 ["Amit",21,85],
 ["Priya",22,90]
]
```

---

# 6. Table Format

Includes schema information.

```python
df.to_json(
    "students.json",
    orient="table"
)
```

---

# Convert JSON into String

Instead of saving a file:

```python
json_data = df.to_json()

print(json_data)
```

---

# Export JSON with Date Format

```python
df.to_json(
    "students.json",
    date_format="iso"
)
```

Example:

```json
"2026-01-15T00:00:00"
```

---

# Export JSON with Indentation

For readable JSON:

```python
df.to_json(
    "students.json",
    orient="records",
    indent=4
)
```

Output:

```json
[
    {
        "Name": "Amit",
        "Age": 21
    }
]
```

---

# Complete Example

```python
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

# Export DataFrame as JSON
df.to_json(
    "students.json",
    orient="records",
    indent=4
)

print("JSON file created successfully!")
```

---

# Read Exported JSON File

```python
df = pd.read_json("students.json")

print(df)
```

---

# Important Parameters of `to_json()`

| Parameter | Purpose |
|-----------|---------|
| `path_or_buf` | JSON file path |
| `orient` | JSON structure format |
| `date_format` | Date representation |
| `double_precision` | Floating point precision |
| `indent` | Pretty formatted JSON |
| `index` | Include index information |

---

In [107]:
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

# Export DataFrame as JSON
df.to_json(
    "students.json",
    orient="records",
    indent=4
)

print("JSON file created successfully!")

JSON file created successfully!

##  Export as SQL

# Export DataFrame as SQL Table 

## What is SQL Export?

Pandas allows us to export a DataFrame into a SQL database table using the `to_sql()` function.

It is used to store analyzed data permanently in databases like:

- SQLite
- MySQL
- PostgreSQL
- SQL Server

---

# Required Libraries

```python
import pandas as pd
import sqlite3
```

---

# Basic Syntax

```python
df.to_sql(
    "table_name",
    connection
)
```

### Explanation:

- `df` → Pandas DataFrame
- `to_sql()` → Writes DataFrame into SQL table
- `"table_name"` → Name of SQL table
- `connection` → Database connection object

---

# Example: Create DataFrame

```python
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)
```

Output:

```
    Name  Age  Marks
0   Amit   21     85
1  Priya   22     90
2  Rahul   20     78
```

---

# Create SQL Database Connection

Using SQLite:

```python
import sqlite3

connection = sqlite3.connect("students.db")
```

This creates:

```
students.db
```

database file.

---

# Export DataFrame to SQL Table

```python
df.to_sql(
    "students",
    connection
)
```

Creates SQL table:

```
students
```

with columns:

```
Name | Age | Marks
```

---

# Complete Example

```python
import pandas as pd
import sqlite3

# Create DataFrame
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)


# Create database connection
connection = sqlite3.connect("students.db")


# Export DataFrame to SQL
df.to_sql(
    "students",
    connection,
    index=False
)


print("Data exported successfully!")


# Close connection
connection.close()
```

---

# Check SQL Table Data

Read the SQL table back into Pandas:

```python
df = pd.read_sql(
    "SELECT * FROM students",
    connection
)

print(df)
```

---

# Avoid Duplicate Table Error

If the table already exists:

```python
df.to_sql(
    "students",
    connection,
    if_exists="replace",
    index=False
)
```

---

# `if_exists` Parameter

Controls what happens when the table already exists.

---

## 1. Replace Existing Table

```python
df.to_sql(
    "students",
    connection,
    if_exists="replace"
)
```

Deletes old table and creates a new one.

---

## 2. Append Data

```python
df.to_sql(
    "students",
    connection,
    if_exists="append"
)
```

Adds new rows to existing table.

---

## 3. Raise Error

```python
df.to_sql(
    "students",
    connection,
    if_exists="fail"
)
```

Default behavior.

Gives error if table already exists.

---

# Remove Index Column

By default, Pandas saves the DataFrame index.

Remove it:

```python
df.to_sql(
    "students",
    connection,
    index=False
)
```

---

# Export Selected Columns

```python
df[["Name","Marks"]].to_sql(
    "student_marks",
    connection,
    index=False
)
```

---

# Export to MySQL Database

Install connector:

```bash
pip install mysql-connector-python
```

Create connection:

```python
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="school"
)
```

Export:

```python
df.to_sql(
    "students",
    connection,
    index=False
)
```

---

# Using SQLAlchemy (Recommended)

Install:

```bash
pip install sqlalchemy
```

Code:

```python
from sqlalchemy import create_engine

engine = create_engine(
    "sqlite:///students.db"
)


df.to_sql(
    "students",
    engine,
    index=False
)
```

---

# Important Parameters of `to_sql()`

| Parameter | Purpose |
|-----------|---------|
| `name` | SQL table name |
| `con` | Database connection |
| `if_exists` | Replace/append/fail |
| `index` | Store DataFrame index |
| `chunksize` | Insert data in batches |
| `dtype` | Specify SQL column types |

---

# Export Large DataFrame in Chunks

```python
df.to_sql(
    "students",
    connection,
    chunksize=1000,
    index=False
)
```

Uploads 1000 rows at a time.